FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine

RUN npm install -g pm2

COPY --from=builder /app /app

WORKDIR /app

COPY wait-for-it.sh .

RUN npx prisma generate

CMD ["sh", "-c", "./wait-for-it.sh db:5432 -- npx prisma migrate deploy && pm2-runtime start ecosystem.config.js"]
