FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ENV NODE_ENV production

EXPOSE 3001

CMD ["pm2-runtime", "start", "dist/main.js", "-i", "max"]